baseURL = 'https://tanvisudhalkar.org/'
languageCode = 'en-us'
title = 'Tanvi Sudhalkar'
theme = 'PaperMod'

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "About me"
name = "About me"
url = "/about"
weight = 20

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"
weight = 30

[[menu.main]]
identifier = "experience"
name = "Experience"
url = "/experience"
weight = 40


[params]
showToc = true
TocOpen = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
hideMeta = false
env = "production"
hideDescriptionInList = false

  [params.profileMode]
  enabled = true
  title = "Tanvi Sudhalkar"
  subtitle = "Hi 👋 I'm Tanvi, a Software/Frontend Developer and a Dancer. Let's connect and create something awesome together!"
  imageUrl = "avatar.png"
  imageWidth = 180
  imageHeight = 200

  [params.cover]
  hiddenInList = false
  hiddenInSingle = false

  [[params.socialIcons]]
  name = "email"
  url = "mailto:tanvi1sudhalkar@gmail.com"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/tanvisudhalkar"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/tanvisudhalkar"

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[markup.goldmark.renderer]
unsafe = true

[build]
  writeStats = true

[build.environment]
  HUGO_VERSION = "0.145.0"